Repository tracim/tracim, pull requests merged in 2019-01, with the labels that each got.

#1301 #1300 fix missing condition in entrypoint
  tools_docker/Debian_Uwsgi/common.sh
  tools_docker/Debian_Uwsgi/entrypoint.sh
  tools_docker/Debian_Uwsgi/uwsgi.ini.sample
Labels: blocker, bug, deployment, quick

#1348 Add documentation for api
  backend/doc/api.md
Labels: documentation

#1349 add migrations script to replace all page slug to html-document
  backend/doc/migrate_from_v1.md
  backend/tracim_backend/migration/versions/354d62d490ad_remove_page_slug_from_properties.py
  backend/tracim_backend/migration/versions/f889c2b59759_remove_page_slug_from_content_revision_.py
Labels: bug, database related

#1347 WIP: replace old user webdav doc from v1
  backend/doc/webdav.md
Labels: documentation

#1340 dont return smtp connection ok when its false + better logs
  backend/tracim_backend/lib/mail_notifier/notifier.py
  backend/tracim_backend/lib/mail_notifier/sender.py
Labels: bug
